import styles from "@pagestyles/Home.module.scss";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import React from "react";

import dynamic from "next/dynamic";

const GameComponent = dynamic(
  () => import("@components/Games/ConfigurationEditor"),
  {
    ssr: false,
  }
);

const Game = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Configuration editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Configuration Editor</h1>

        <p className={styles.description}>
          Edit configuration and press <b>clearAndGenerate</b>
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.gameCanvas}>
          <GameComponent />
        </div>
      </main>
    </div>
  );
};

export default Game;
