import styles from "@pagestyles/Home.module.scss";
import Head from "next/head";
import React from "react";

import dynamic from "next/dynamic";
import classNames from "classnames";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSideProps } from "next";

const GameComponent = dynamic(
  () => import("@components/Games/ConfigurationEditor"),
  {
    ssr: false,
  }
);

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: { ...(await serverSideTranslations(context.locale!, ["common"])) },
  };
};

const Game = () => {
  const { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>{t("Configuration editor")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classNames(styles.main, styles.noOverflow)}>
        <h1 className={styles.title}>{t("Welcome to Configuration Editor")}</h1>

        <p className={styles.description}>
          {t("Edit configuration and press")} <b>clearAndGenerate</b>
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.gameCanvas}>
          <GameComponent />
        </div>
      </main>
    </div>
  );
};

export default Game;
