import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Box, Grid, GridItem, Link, Text } from "@chakra-ui/react";

const links = [
  {
    link: "/game",
    heading: "Configuration builder",
    text: "Build your own configuration",
  },
  {
    link: "/proto/App",
    heading: "PSVT:R Test",
    text: "Test your mental rotation abilities",
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PSVT:R</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to digitalized configurable PSVT:R
        </h1>

        <p className={styles.description}>
          Get started by visiting the following links:
        </p>

        <Grid mt={"2rem"} templateColumns={"1fr 1fr"} gap={"2rem"}>
          {links.map(({ link, heading, text }) => (
            <GridItem
              p={"2rem"}
              border={"1px solid transparent"}
              borderRadius={"2rem"}
              transition="transform ease-in-out .2s, box-shadow ease-in-out .2s, border-color ease-in-out .2s"
              sx={{
                _hover: {
                  transform: "scale(1.05)",
                  border: "1px solid #63B3ED",
                  boxShadow: "1rem 1rem 3rem #bee0ec",
                },
              }}
            >
              <Link href={link}>
                <h2>{heading} &rarr;</h2>
                <p>{text}</p>
              </Link>
            </GridItem>
          ))}
        </Grid>
      </main>

      <footer className={styles.footer}>
        <Box textAlign={"center"}>
          Made by <Text as={"b"}>Dmitry Voronov</Text>
        </Box>
      </footer>
    </div>
  );
};

export default Home;
