create or replace function get_first_additional_test_per_user(testType "AdditionalTestType")
    returns table
            (
                "userId"    text,
                id          text,
                "createdAt" timestamp(3),
                type        "AdditionalTestType",
                data        jsonb
            )
as
$$
begin
    return query select distinct on ("userId") ADT."userId", ADT.id, ADT."createdAt", ADT.type, ADT.data
                 from "AdditionalTest" ADT
                 where ADT.type = testType
                 order by ADT."userId";
end
$$ language plpgsql;

create or replace function get_user_info_data()
    returns table
            (
                "id"                            text,
                "testGroup"                     integer,
                "userId"                        text,
                "age"                           integer,
                "gender"                        text,
                "occupation"                    text,
                "isRightHanded"                 integer,
                "academicField"                 text,
                "hasNeurodegenerativeIllnesses" text
            )
as
$$
begin
    return query select UI.id,
--        info,
                        UI."testGroup",
                        UI."userId",
                        (UI.info::json ->> 'age')::integer                        as age,
                        (UI.info::json ->> 'gender')::text                        as gender,
                        (UI.info::json ->> 'occupation')::text                    as occupation,
                        ((UI.info::json ->> 'isRightHanded')::bool)::integer                 as "isRightHanded",
                        (UI.info::json ->> 'academicField')::text                 as "academicField",
--              TODO: make all strings
                        (UI.info::json ->> 'hasNeurodegenerativeIllnesses')::text as "hasNeurodegenerativeIllnesses"
                 from "UserInfo" as UI;
end
$$ language plpgsql;


-- all user additional test data
create or replace function get_depression_test_data()
    returns table
            (
                "userId"           text,
                "id"               text,
                "createdAt"        timestamp(3),
                "type"             "AdditionalTestType",
                "PHQ-0 total"      integer,
                "PHQ-9 question 1" integer,
                "PHQ-9 question 2" integer,
                "PHQ-9 question 3" integer,
                "PHQ-9 question 4" integer,
                "PHQ-9 question 5" integer,
                "PHQ-9 question 6" integer,
                "PHQ-9 question 7" integer,
                "PHQ-9 question 8" integer
            )
as
$$
begin
    return query select "FirstDepressionTest"."userId",
                        "FirstDepressionTest".id,
                        "FirstDepressionTest"."createdAt",
                        "FirstDepressionTest".type,
                        ("FirstDepressionTest".data::json ->> 'total')::integer as "PHQ-0 total",
                        ("FirstDepressionTest".data::json ->> '0')::integer     as "PHQ-9 question 1",
                        ("FirstDepressionTest".data::json ->> '1')::integer     as "PHQ-9 question 2",
                        ("FirstDepressionTest".data::json ->> '2')::integer     as "PHQ-9 question 3",
                        ("FirstDepressionTest".data::json ->> '3')::integer     as "PHQ-9 question 4",
                        ("FirstDepressionTest".data::json ->> '4')::integer     as "PHQ-9 question 5",
                        ("FirstDepressionTest".data::json ->> '5')::integer     as "PHQ-9 question 6",
                        ("FirstDepressionTest".data::json ->> '6')::integer     as "PHQ-9 question 7",
                        ("FirstDepressionTest".data::json ->> '7')::integer     as "PHQ-9 question 8"
                 from (select *
                       from get_first_additional_test_per_user(testType := 'PHQ9')) as "FirstDepressionTest";
end
$$ language plpgsql;


create or replace function get_emotion_test_data()
    returns table
            (
                "userId"          text,
                "id"              text,
                "createdAt"       timestamp(3),
                "type"            "AdditionalTestType",
                "Bauda"           integer,
                "Kauns"           integer,
                "Naids"           integer,
                "Vaina"           integer,
                "Bailes"          integer,
                "Dusmas"          integer,
                "Prieks"          integer,
                "Lepnums"         integer,
                "Nozela"          integer,
                "Riebums"         integer,
                "Skumjas"         integer,
                "Apbrina"         integer,
                "Interese"        integer,
                "Milestiba"       integer,
                "Milestiba2"      integer,
                "Vilsanas"        integer,
                "Nicinajums"      integer,
                "Atvieglojums"    integer,
                "Lidzjutiba"      integer,
                "Apmierinajums"   integer,
                "Uzjautrinajums"  integer,
                "Another emotion" text,
                "totalpoints"     integer
            )
as
$$
begin
    return query select *,
                        (ET."Bauda" +
                         ET."Kauns" +
                         ET."Naids" +
                         ET."Vaina" +
                         ET."Bailes" +
                         ET."Dusmas" +
                         ET."Prieks" +
                         ET."Lepnums" +
                         ET."Nozela" +
                         ET."Riebums" +
                         ET."Skumjas" +
                         ET."Apbrina" +
                         ET."Interese" +
                         coalesce(ET."Milestiba", 0) +
                         coalesce(ET."Milestiba2", 0) +
                         ET."Vilsanas" +
                         ET."Nicinajums" +
                         ET."Atvieglojums" +
                         ET."Lidzjutiba" +
                         ET."Apmierinajums" +
                         ET."Uzjautrinajums") "totalPoints"
                 from (select FirstEmotionTest."userId",
                              FirstEmotionTest.id,
                              FirstEmotionTest."createdAt",
                              FirstEmotionTest.type,
                              (data::json ->> 'Bauda')::integer          as "Bauda",
                              (data::json ->> 'Kauns')::integer          as "Kauns",
                              (data::json ->> 'Naids')::integer          as "Naids",
                              (data::json ->> 'Vaina')::integer          as "Vaina",
                              (data::json ->> 'Bailes')::integer         as "Bailes",
                              (data::json ->> 'Dusmas')::integer         as "Dusmas",
                              (data::json ->> 'Prieks')::integer         as "Prieks",
                              (data::json ->> 'Lepnums')::integer        as "Lepnums",
                              (data::json ->> 'Nožela')::integer         as "Nozela",
                              (data::json ->> 'Riebums')::integer        as "Riebums",
                              (data::json ->> 'Skumjas')::integer        as "Skumjas",
                              (data::json ->> 'Apbrīna')::integer        as "Apbrina",
                              (data::json ->> 'Interese')::integer       as "Interese",
                              (data::json ->> 'Milestība')::integer      as "Milestiba",
                              (data::json ->> 'Mīlestība')::integer      as "Milestiba2",
                              (data::json ->> 'Vilšanās')::integer       as "Vilsanas",
                              (data::json ->> 'Nicinājums')::integer     as "Nicinajums",
                              (data::json ->> 'Atvieglojums')::integer   as "Atvieglojums",
                              (data::json ->> 'Līdzjutība')::integer     as "Lidzjutiba",
                              (data::json ->> 'Apmierinājums')::integer  as "Apmierinajums",
                              (data::json ->> 'Uzjautrinājums')::integer as "Uzjautrinajums",
                              (data::json ->> 'other')::text             as "Another emotion"
                       from (select *
                             from get_first_additional_test_per_user(testType := 'EMOTION_WHEEL')) as FirstEmotionTest) ET;
end
$$ language plpgsql;


create or replace function get_actual_test_data()
    returns table
            (
                "id"                      text,
                "createdAt"               timestamp(3),
                "userId"                  text,
                "testId"                  text,
                "task1_completed_answer"  integer,
                "task2_completed_answer"  integer,
                "task3_completed_answer"  integer,
                "task4_completed_answer"  integer,
                "task5_completed_answer"  integer,
                "task6_completed_answer"  integer,
                "task7_completed_answer"  integer,
                "task8_completed_answer"  integer,
                "task9_completed_answer"  integer,
                "task10_completed_answer" integer,
                "task11_completed_answer" integer,
                "task12_completed_answer" integer,
                "task13_completed_answer" integer,
                "task14_completed_answer" integer,
                "task15_completed_answer" integer,
                "task16_completed_answer" integer,
                "task17_completed_answer" integer,
                "task18_completed_answer" integer,
                "task19_completed_answer" integer,
                "task20_completed_answer" integer,
                "task21_completed_answer" integer,
                "task22_completed_answer" integer,
                "task23_completed_answer" integer,
                "task24_completed_answer" integer,
                "task1_completed_time"    double precision,
                "task2_completed_time"    double precision,
                "task3_completed_time"    double precision,
                "task4_completed_time"    double precision,
                "task5_completed_time"    double precision,
                "task6_completed_time"    double precision,
                "task7_completed_time"    double precision,
                "task8_completed_time"    double precision,
                "task9_completed_time"    double precision,
                "task10_completed_time"   double precision,
                "task11_completed_time"   double precision,
                "task12_completed_time"   double precision,
                "task13_completed_time"   double precision,
                "task14_completed_time"   double precision,
                "task15_completed_time"   double precision,
                "task16_completed_time"   double precision,
                "task17_completed_time"   double precision,
                "task18_completed_time"   double precision,
                "task19_completed_time"   double precision,
                "task20_completed_time"   double precision,
                "task21_completed_time"   double precision,
                "task22_completed_time"   double precision,
                "task23_completed_time"   double precision,
                "task24_completed_time"   double precision,
                "task1_isCorrect"         integer,
                "task2_isCorrect"         integer,
                "task3_isCorrect"         integer,
                "task4_isCorrect"         integer,
                "task5_isCorrect"         integer,
                "task6_isCorrect"         integer,
                "task7_isCorrect"         integer,
                "task8_isCorrect"         integer,
                "task9_isCorrect"         integer,
                "task10_isCorrect"        integer,
                "task11_isCorrect"        integer,
                "task12_isCorrect"        integer,
                "task13_isCorrect"        integer,
                "task14_isCorrect"        integer,
                "task15_isCorrect"        integer,
                "task16_isCorrect"        integer,
                "task17_isCorrect"        integer,
                "task18_isCorrect"        integer,
                "task19_isCorrect"        integer,
                "task20_isCorrect"        integer,
                "task21_isCorrect"        integer,
                "task22_isCorrect"        integer,
                "task23_isCorrect"        integer,
                "task24_isCorrect"        integer,


                "total_isCorrect"         integer
            )
as
$$
begin
    return query select *,
                        (
                                C."task1_isCorrect" +
                                C."task2_isCorrect" +
                                C."task3_isCorrect" +
                                C."task4_isCorrect" +
                                C."task5_isCorrect" +
                                C."task6_isCorrect" +
                                C."task7_isCorrect" +
                                C."task8_isCorrect" +
                                C."task9_isCorrect" +
                                C."task10_isCorrect" +
                                C."task11_isCorrect" +
                                C."task12_isCorrect" +
                                C."task13_isCorrect" +
                                C."task14_isCorrect" +
                                C."task15_isCorrect" +
                                C."task16_isCorrect" +
                                C."task17_isCorrect" +
                                C."task18_isCorrect" +
                                C."task19_isCorrect" +
                                C."task20_isCorrect" +
                                C."task21_isCorrect" +
                                C."task22_isCorrect" +
                                C."task23_isCorrect" +
                                C."task24_isCorrect"
                            ) "total_isCorrect"
                 from (select CCT.id,
                              CCT."createdAt",
                              CCT."userId",
                              CCT."testId",
                              --        CCT.time,
                              --        CCT."actualAnswer",
                              --        CCT.correct,

                              CCT."actualAnswer"[1]  "task1_completed_answer",
                              CCT."actualAnswer"[2]  "task2_completed_answer",
                              CCT."actualAnswer"[3]  "task3_completed_answer",
                              CCT."actualAnswer"[4]  "task4_completed_answer",
                              CCT."actualAnswer"[5]  "task5_completed_answer",
                              CCT."actualAnswer"[6]  "task6_completed_answer",
                              CCT."actualAnswer"[7]  "task7_completed_answer",
                              CCT."actualAnswer"[8]  "task8_completed_answer",
                              CCT."actualAnswer"[9]  "task9_completed_answer",
                              CCT."actualAnswer"[10] "task10_completed_answer",
                              CCT."actualAnswer"[11] "task11_completed_answer",
                              CCT."actualAnswer"[12] "task12_completed_answer",
                              CCT."actualAnswer"[13] "task13_completed_answer",
                              CCT."actualAnswer"[14] "task14_completed_answer",
                              CCT."actualAnswer"[15] "task15_completed_answer",
                              CCT."actualAnswer"[16] "task16_completed_answer",
                              CCT."actualAnswer"[17] "task17_completed_answer",
                              CCT."actualAnswer"[18] "task18_completed_answer",
                              CCT."actualAnswer"[19] "task19_completed_answer",
                              CCT."actualAnswer"[20] "task20_completed_answer",
                              CCT."actualAnswer"[21] "task21_completed_answer",
                              CCT."actualAnswer"[22] "task22_completed_answer",
                              CCT."actualAnswer"[23] "task23_completed_answer",
                              CCT."actualAnswer"[24] "task24_completed_answer",
                              time[1]                "task1_completed_time",
                              time[2]                "task2_completed_time",
                              time[3]                "task3_completed_time",
                              time[4]                "task4_completed_time",
                              time[5]                "task5_completed_time",
                              time[6]                "task6_completed_time",
                              time[7]                "task7_completed_time",
                              time[8]                "task8_completed_time",
                              time[9]                "task9_completed_time",
                              time[10]               "task10_completed_time",
                              time[11]               "task11_completed_time",
                              time[12]               "task12_completed_time",
                              time[13]               "task13_completed_time",
                              time[14]               "task14_completed_time",
                              time[15]               "task15_completed_time",
                              time[16]               "task16_completed_time",
                              time[17]               "task17_completed_time",
                              time[18]               "task18_completed_time",
                              time[19]               "task19_completed_time",
                              time[20]               "task20_completed_time",
                              time[21]               "task21_completed_time",
                              time[22]               "task22_completed_time",
                              time[23]               "task23_completed_time",
                              time[24]               "task24_completed_time",
                              correct[1] ::integer   "task1_isCorrect",
                              correct[2] ::integer   "task2_isCorrect",
                              correct[3] ::integer   "task3_isCorrect",
                              correct[4] ::integer   "task4_isCorrect",
                              correct[5] ::integer   "task5_isCorrect",
                              correct[6] ::integer   "task6_isCorrect",
                              correct[7] ::integer   "task7_isCorrect",
                              correct[8] ::integer   "task8_isCorrect",
                              correct[9] ::integer   "task9_isCorrect",
                              correct[10]::integer   "task10_isCorrect",
                              correct[11]::integer   "task11_isCorrect",
                              correct[12]::integer   "task12_isCorrect",
                              correct[13]::integer   "task13_isCorrect",
                              correct[14]::integer   "task14_isCorrect",
                              correct[15]::integer   "task15_isCorrect",
                              correct[16]::integer   "task16_isCorrect",
                              correct[17]::integer   "task17_isCorrect",
                              correct[18]::integer   "task18_isCorrect",
                              correct[19]::integer   "task19_isCorrect",
                              correct[20]::integer   "task20_isCorrect",
                              correct[21]::integer   "task21_isCorrect",
                              correct[22]::integer   "task22_isCorrect",
                              correct[23]::integer   "task23_isCorrect",
                              correct[24]::integer   "task24_isCorrect"

                       from (select CTe.id,
                                    CTe."createdAt",
                                    CTe."userId",
                                    CTe."testId",
                                    array_agg(CTa.time)    time,
                                    array_agg(CTa.answer)  "actualAnswer",
                                    array_agg(CTa.correct) correct

                             from "CompletedTest" CTe
                                      join "CompletedTask" CTa on CTe.id = CTa."testId"
                             group by CTe.id, CTe."createdAt", CTe."userId", CTe."testId") CCT) C;
end
$$ language plpgsql;

CREATE EXTENSION IF NOT EXISTS tablefunc;



----------------------
------------------------
---------------------------

(select *
 from (select
--     task 1
(AT.angles[1] ->> 'rotationX'):: integer                                  "task1_rotationX",
(AT.angles[1] ->> 'rotationY'):: integer                                  "task1_rotationY",
(AT.angles[1] ->> 'rotationZ'):: integer                                  "task1_rotationZ",
(AT."referenceShape"[1] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task1_reference-spreadOnX",
(AT."referenceShape"[1] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task1_reference-spreadOnY",
(AT."referenceShape"[1] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task1_reference-spreadOnZ",
(AT."referenceShape"[1] ->> 'reference-totalBlocks') :: integer           "task1_reference-totalBlocks",
(AT."referenceShape"[1] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task1_reference-finalRotationX",
(AT."referenceShape"[1] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task1_reference-finalRotationY",
(AT."referenceShape"[1] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task1_reference-finalRotationZ",
(AT."referenceShape"[1] ->> 'reference-maxDeltaForNextBlock') :: integer  "task1_reference-maxDeltaForNextBlock",
(AT."targetShape"[1] ->> 'target-spreadOnX') :: numeric(3, 2)             "task1_target-spreadOnX",
(AT."targetShape"[1] ->> 'target-spreadOnY') :: numeric(3, 2)             "task1_target-spreadOnY",
(AT."targetShape"[1] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task1_target-spreadOnZ",
(AT."targetShape"[1] ->> 'target-totalBlocks') :: integer                 "task1_target-totalBlocks",
(AT."targetShape"[1] ->> 'target-finalRotationX') :: numeric(3, 2)        "task1_target-finalRotationX",
(AT."targetShape"[1] ->> 'target-finalRotationY') :: numeric(3, 2)        "task1_target-finalRotationY",
(AT."targetShape"[1] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task1_target-finalRotationZ",
(AT."targetShape"[1] ->> 'target-maxDeltaForNextBlock') :: integer        "task1_target-maxDeltaForNextBlock",
(AT."images"[1] ->> 'scene') :: text                                      "task1_img-scene",
(AT."images"[1] ->> 'testShape') :: text                                  "task1_img-testShape",
(AT."images"[1] ->> 'testShape1') :: text                                 "task1_img-testShape1",
(AT."images"[1] ->> 'testShape2') :: text                                 "task1_img-testShape2",
(AT."images"[1] ->> 'testShape3') :: text                                 "task1_img-testShape3",
(AT."images"[1] ->> 'testShape4') :: text                                 "task1_img-testShape4",
(AT."images"[1] ->> 'testShape5') :: text                                 "task1_img-testShape5",
(AT."images"[1] ->> 'referenceShape') :: text                             "task1_img-referenceShape",
(AT."images"[1] ->> 'referenceShapeRotated') :: text                      "task1_img-referenceShapeRotated",
AT."correctAnswer"[1]                                                     "task1_correctAnswer",

--     task 2
(AT.angles[2] ->> 'rotationX'):: integer                                  "task2_rotationX",
(AT.angles[2] ->> 'rotationY'):: integer                                  "task2_rotationY",
(AT.angles[2] ->> 'rotationZ'):: integer                                  "task2_rotationZ",
(AT."referenceShape"[2] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task2_reference-spreadOnX",
(AT."referenceShape"[2] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task2_reference-spreadOnY",
(AT."referenceShape"[2] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task2_reference-spreadOnZ",
(AT."referenceShape"[2] ->> 'reference-totalBlocks') :: integer           "task2_reference-totalBlocks",
(AT."referenceShape"[2] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task2_reference-finalRotationX",
(AT."referenceShape"[2] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task2_reference-finalRotationY",
(AT."referenceShape"[2] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task2_reference-finalRotationZ",
(AT."referenceShape"[2] ->> 'reference-maxDeltaForNextBlock') :: integer  "task2_reference-maxDeltaForNextBlock",
(AT."targetShape"[2] ->> 'target-spreadOnX') :: numeric(3, 2)             "task2_target-spreadOnX",
(AT."targetShape"[2] ->> 'target-spreadOnY') :: numeric(3, 2)             "task2_target-spreadOnY",
(AT."targetShape"[2] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task2_target-spreadOnZ",
(AT."targetShape"[2] ->> 'target-totalBlocks') :: integer                 "task2_target-totalBlocks",
(AT."targetShape"[2] ->> 'target-finalRotationX') :: numeric(3, 2)        "task2_target-finalRotationX",
(AT."targetShape"[2] ->> 'target-finalRotationY') :: numeric(3, 2)        "task2_target-finalRotationY",
(AT."targetShape"[2] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task2_target-finalRotationZ",
(AT."targetShape"[2] ->> 'target-maxDeltaForNextBlock') :: integer        "task2_target-maxDeltaForNextBlock",
(AT."images"[2] ->> 'scene') :: text                                      "task2_img-scene",
(AT."images"[2] ->> 'testShape') :: text                                  "task2_img-testShape",
(AT."images"[2] ->> 'testShape1') :: text                                 "task2_img-testShape1",
(AT."images"[2] ->> 'testShape2') :: text                                 "task2_img-testShape2",
(AT."images"[2] ->> 'testShape3') :: text                                 "task2_img-testShape3",
(AT."images"[2] ->> 'testShape4') :: text                                 "task2_img-testShape4",
(AT."images"[2] ->> 'testShape5') :: text                                 "task2_img-testShape5",
(AT."images"[2] ->> 'referenceShape') :: text                             "task2_img-referenceShape",
(AT."images"[2] ->> 'referenceShapeRotated') :: text                      "task2_img-referenceShapeRotated",
AT."correctAnswer"[2]                                                     "task2_correctAnswer",

--     task 3
(AT.angles[3] ->> 'rotationX'):: integer                                  "task3_rotationX",
(AT.angles[3] ->> 'rotationY'):: integer                                  "task3_rotationY",
(AT.angles[3] ->> 'rotationZ'):: integer                                  "task3_rotationZ",
(AT."referenceShape"[3] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task3_reference-spreadOnX",
(AT."referenceShape"[3] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task3_reference-spreadOnY",
(AT."referenceShape"[3] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task3_reference-spreadOnZ",
(AT."referenceShape"[3] ->> 'reference-totalBlocks') :: integer           "task3_reference-totalBlocks",
(AT."referenceShape"[3] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task3_reference-finalRotationX",
(AT."referenceShape"[3] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task3_reference-finalRotationY",
(AT."referenceShape"[3] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task3_reference-finalRotationZ",
(AT."referenceShape"[3] ->> 'reference-maxDeltaForNextBlock') :: integer  "task3_reference-maxDeltaForNextBlock",
(AT."targetShape"[3] ->> 'target-spreadOnX') :: numeric(3, 2)             "task3_target-spreadOnX",
(AT."targetShape"[3] ->> 'target-spreadOnY') :: numeric(3, 2)             "task3_target-spreadOnY",
(AT."targetShape"[3] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task3_target-spreadOnZ",
(AT."targetShape"[3] ->> 'target-totalBlocks') :: integer                 "task3_target-totalBlocks",
(AT."targetShape"[3] ->> 'target-finalRotationX') :: numeric(3, 2)        "task3_target-finalRotationX",
(AT."targetShape"[3] ->> 'target-finalRotationY') :: numeric(3, 2)        "task3_target-finalRotationY",
(AT."targetShape"[3] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task3_target-finalRotationZ",
(AT."targetShape"[3] ->> 'target-maxDeltaForNextBlock') :: integer        "task3_target-maxDeltaForNextBlock",
(AT."images"[3] ->> 'scene') :: text                                      "task3_img-scene",
(AT."images"[3] ->> 'testShape') :: text                                  "task3_img-testShape",
(AT."images"[3] ->> 'testShape1') :: text                                 "task3_img-testShape1",
(AT."images"[3] ->> 'testShape2') :: text                                 "task3_img-testShape2",
(AT."images"[3] ->> 'testShape3') :: text                                 "task3_img-testShape3",
(AT."images"[3] ->> 'testShape4') :: text                                 "task3_img-testShape4",
(AT."images"[3] ->> 'testShape5') :: text                                 "task3_img-testShape5",
(AT."images"[3] ->> 'referenceShape') :: text                             "task3_img-referenceShape",
(AT."images"[3] ->> 'referenceShapeRotated') :: text                      "task3_img-referenceShapeRotated",
AT."correctAnswer"[3]                                                     "task3_correctAnswer",

--     task 4
(AT.angles[4] ->> 'rotationX'):: integer                                  "task4_rotationX",
(AT.angles[4] ->> 'rotationY'):: integer                                  "task4_rotationY",
(AT.angles[4] ->> 'rotationZ'):: integer                                  "task4_rotationZ",
(AT."referenceShape"[4] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task4_reference-spreadOnX",
(AT."referenceShape"[4] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task4_reference-spreadOnY",
(AT."referenceShape"[4] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task4_reference-spreadOnZ",
(AT."referenceShape"[4] ->> 'reference-totalBlocks') :: integer           "task4_reference-totalBlocks",
(AT."referenceShape"[4] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task4_reference-finalRotationX",
(AT."referenceShape"[4] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task4_reference-finalRotationY",
(AT."referenceShape"[4] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task4_reference-finalRotationZ",
(AT."referenceShape"[4] ->> 'reference-maxDeltaForNextBlock') :: integer  "task4_reference-maxDeltaForNextBlock",
(AT."targetShape"[4] ->> 'target-spreadOnX') :: numeric(3, 2)             "task4_target-spreadOnX",
(AT."targetShape"[4] ->> 'target-spreadOnY') :: numeric(3, 2)             "task4_target-spreadOnY",
(AT."targetShape"[4] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task4_target-spreadOnZ",
(AT."targetShape"[4] ->> 'target-totalBlocks') :: integer                 "task4_target-totalBlocks",
(AT."targetShape"[4] ->> 'target-finalRotationX') :: numeric(3, 2)        "task4_target-finalRotationX",
(AT."targetShape"[4] ->> 'target-finalRotationY') :: numeric(3, 2)        "task4_target-finalRotationY",
(AT."targetShape"[4] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task4_target-finalRotationZ",
(AT."targetShape"[4] ->> 'target-maxDeltaForNextBlock') :: integer        "task4_target-maxDeltaForNextBlock",
(AT."images"[4] ->> 'scene') :: text                                      "task4_img-scene",
(AT."images"[4] ->> 'testShape') :: text                                  "task4_img-testShape",
(AT."images"[4] ->> 'testShape1') :: text                                 "task4_img-testShape1",
(AT."images"[4] ->> 'testShape2') :: text                                 "task4_img-testShape2",
(AT."images"[4] ->> 'testShape3') :: text                                 "task4_img-testShape3",
(AT."images"[4] ->> 'testShape4') :: text                                 "task4_img-testShape4",
(AT."images"[4] ->> 'testShape5') :: text                                 "task4_img-testShape5",
(AT."images"[4] ->> 'referenceShape') :: text                             "task4_img-referenceShape",
(AT."images"[4] ->> 'referenceShapeRotated') :: text                      "task4_img-referenceShapeRotated",
AT."correctAnswer"[4]                                                     "task4_correctAnswer",

--     task 5
(AT.angles[5] ->> 'rotationX'):: integer                                  "task5_rotationX",
(AT.angles[5] ->> 'rotationY'):: integer                                  "task5_rotationY",
(AT.angles[5] ->> 'rotationZ'):: integer                                  "task5_rotationZ",
(AT."referenceShape"[5] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task5_reference-spreadOnX",
(AT."referenceShape"[5] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task5_reference-spreadOnY",
(AT."referenceShape"[5] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task5_reference-spreadOnZ",
(AT."referenceShape"[5] ->> 'reference-totalBlocks') :: integer           "task5_reference-totalBlocks",
(AT."referenceShape"[5] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task5_reference-finalRotationX",
(AT."referenceShape"[5] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task5_reference-finalRotationY",
(AT."referenceShape"[5] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task5_reference-finalRotationZ",
(AT."referenceShape"[5] ->> 'reference-maxDeltaForNextBlock') :: integer  "task5_reference-maxDeltaForNextBlock",
(AT."targetShape"[5] ->> 'target-spreadOnX') :: numeric(3, 2)             "task5_target-spreadOnX",
(AT."targetShape"[5] ->> 'target-spreadOnY') :: numeric(3, 2)             "task5_target-spreadOnY",
(AT."targetShape"[5] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task5_target-spreadOnZ",
(AT."targetShape"[5] ->> 'target-totalBlocks') :: integer                 "task5_target-totalBlocks",
(AT."targetShape"[5] ->> 'target-finalRotationX') :: numeric(3, 2)        "task5_target-finalRotationX",
(AT."targetShape"[5] ->> 'target-finalRotationY') :: numeric(3, 2)        "task5_target-finalRotationY",
(AT."targetShape"[5] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task5_target-finalRotationZ",
(AT."targetShape"[5] ->> 'target-maxDeltaForNextBlock') :: integer        "task5_target-maxDeltaForNextBlock",
(AT."images"[5] ->> 'scene') :: text                                      "task5_img-scene",
(AT."images"[5] ->> 'testShape') :: text                                  "task5_img-testShape",
(AT."images"[5] ->> 'testShape1') :: text                                 "task5_img-testShape1",
(AT."images"[5] ->> 'testShape2') :: text                                 "task5_img-testShape2",
(AT."images"[5] ->> 'testShape3') :: text                                 "task5_img-testShape3",
(AT."images"[5] ->> 'testShape4') :: text                                 "task5_img-testShape4",
(AT."images"[5] ->> 'testShape5') :: text                                 "task5_img-testShape5",
(AT."images"[5] ->> 'referenceShape') :: text                             "task5_img-referenceShape",
(AT."images"[5] ->> 'referenceShapeRotated') :: text                      "task5_img-referenceShapeRotated",
AT."correctAnswer"[5]                                                     "task5_correctAnswer",

--     task 6
(AT.angles[6] ->> 'rotationX'):: integer                                  "task6_rotationX",
(AT.angles[6] ->> 'rotationY'):: integer                                  "task6_rotationY",
(AT.angles[6] ->> 'rotationZ'):: integer                                  "task6_rotationZ",
(AT."referenceShape"[6] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task6_reference-spreadOnX",
(AT."referenceShape"[6] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task6_reference-spreadOnY",
(AT."referenceShape"[6] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task6_reference-spreadOnZ",
(AT."referenceShape"[6] ->> 'reference-totalBlocks') :: integer           "task6_reference-totalBlocks",
(AT."referenceShape"[6] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task6_reference-finalRotationX",
(AT."referenceShape"[6] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task6_reference-finalRotationY",
(AT."referenceShape"[6] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task6_reference-finalRotationZ",
(AT."referenceShape"[6] ->> 'reference-maxDeltaForNextBlock') :: integer  "task6_reference-maxDeltaForNextBlock",
(AT."targetShape"[6] ->> 'target-spreadOnX') :: numeric(3, 2)             "task6_target-spreadOnX",
(AT."targetShape"[6] ->> 'target-spreadOnY') :: numeric(3, 2)             "task6_target-spreadOnY",
(AT."targetShape"[6] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task6_target-spreadOnZ",
(AT."targetShape"[6] ->> 'target-totalBlocks') :: integer                 "task6_target-totalBlocks",
(AT."targetShape"[6] ->> 'target-finalRotationX') :: numeric(3, 2)        "task6_target-finalRotationX",
(AT."targetShape"[6] ->> 'target-finalRotationY') :: numeric(3, 2)        "task6_target-finalRotationY",
(AT."targetShape"[6] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task6_target-finalRotationZ",
(AT."targetShape"[6] ->> 'target-maxDeltaForNextBlock') :: integer        "task6_target-maxDeltaForNextBlock",
(AT."images"[6] ->> 'scene') :: text                                      "task6_img-scene",
(AT."images"[6] ->> 'testShape') :: text                                  "task6_img-testShape",
(AT."images"[6] ->> 'testShape1') :: text                                 "task6_img-testShape1",
(AT."images"[6] ->> 'testShape2') :: text                                 "task6_img-testShape2",
(AT."images"[6] ->> 'testShape3') :: text                                 "task6_img-testShape3",
(AT."images"[6] ->> 'testShape4') :: text                                 "task6_img-testShape4",
(AT."images"[6] ->> 'testShape5') :: text                                 "task6_img-testShape5",
(AT."images"[6] ->> 'referenceShape') :: text                             "task6_img-referenceShape",
(AT."images"[6] ->> 'referenceShapeRotated') :: text                      "task6_img-referenceShapeRotated",
AT."correctAnswer"[6]                                                     "task6_correctAnswer",

--     task 7
(AT.angles[7] ->> 'rotationX'):: integer                                  "task7_rotationX",
(AT.angles[7] ->> 'rotationY'):: integer                                  "task7_rotationY",
(AT.angles[7] ->> 'rotationZ'):: integer                                  "task7_rotationZ",
(AT."referenceShape"[7] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task7_reference-spreadOnX",
(AT."referenceShape"[7] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task7_reference-spreadOnY",
(AT."referenceShape"[7] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task7_reference-spreadOnZ",
(AT."referenceShape"[7] ->> 'reference-totalBlocks') :: integer           "task7_reference-totalBlocks",
(AT."referenceShape"[7] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task7_reference-finalRotationX",
(AT."referenceShape"[7] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task7_reference-finalRotationY",
(AT."referenceShape"[7] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task7_reference-finalRotationZ",
(AT."referenceShape"[7] ->> 'reference-maxDeltaForNextBlock') :: integer  "task7_reference-maxDeltaForNextBlock",
(AT."targetShape"[7] ->> 'target-spreadOnX') :: numeric(3, 2)             "task7_target-spreadOnX",
(AT."targetShape"[7] ->> 'target-spreadOnY') :: numeric(3, 2)             "task7_target-spreadOnY",
(AT."targetShape"[7] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task7_target-spreadOnZ",
(AT."targetShape"[7] ->> 'target-totalBlocks') :: integer                 "task7_target-totalBlocks",
(AT."targetShape"[7] ->> 'target-finalRotationX') :: numeric(3, 2)        "task7_target-finalRotationX",
(AT."targetShape"[7] ->> 'target-finalRotationY') :: numeric(3, 2)        "task7_target-finalRotationY",
(AT."targetShape"[7] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task7_target-finalRotationZ",
(AT."targetShape"[7] ->> 'target-maxDeltaForNextBlock') :: integer        "task7_target-maxDeltaForNextBlock",
(AT."images"[7] ->> 'scene') :: text                                      "task7_img-scene",
(AT."images"[7] ->> 'testShape') :: text                                  "task7_img-testShape",
(AT."images"[7] ->> 'testShape1') :: text                                 "task7_img-testShape1",
(AT."images"[7] ->> 'testShape2') :: text                                 "task7_img-testShape2",
(AT."images"[7] ->> 'testShape3') :: text                                 "task7_img-testShape3",
(AT."images"[7] ->> 'testShape4') :: text                                 "task7_img-testShape4",
(AT."images"[7] ->> 'testShape5') :: text                                 "task7_img-testShape5",
(AT."images"[7] ->> 'referenceShape') :: text                             "task7_img-referenceShape",
(AT."images"[7] ->> 'referenceShapeRotated') :: text                      "task7_img-referenceShapeRotated",
AT."correctAnswer"[7]                                                     "task7_correctAnswer",

--     task 8
(AT.angles[8] ->> 'rotationX'):: integer                                  "task8_rotationX",
(AT.angles[8] ->> 'rotationY'):: integer                                  "task8_rotationY",
(AT.angles[8] ->> 'rotationZ'):: integer                                  "task8_rotationZ",
(AT."referenceShape"[8] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task8_reference-spreadOnX",
(AT."referenceShape"[8] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task8_reference-spreadOnY",
(AT."referenceShape"[8] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task8_reference-spreadOnZ",
(AT."referenceShape"[8] ->> 'reference-totalBlocks') :: integer           "task8_reference-totalBlocks",
(AT."referenceShape"[8] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task8_reference-finalRotationX",
(AT."referenceShape"[8] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task8_reference-finalRotationY",
(AT."referenceShape"[8] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task8_reference-finalRotationZ",
(AT."referenceShape"[8] ->> 'reference-maxDeltaForNextBlock') :: integer  "task8_reference-maxDeltaForNextBlock",
(AT."targetShape"[8] ->> 'target-spreadOnX') :: numeric(3, 2)             "task8_target-spreadOnX",
(AT."targetShape"[8] ->> 'target-spreadOnY') :: numeric(3, 2)             "task8_target-spreadOnY",
(AT."targetShape"[8] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task8_target-spreadOnZ",
(AT."targetShape"[8] ->> 'target-totalBlocks') :: integer                 "task8_target-totalBlocks",
(AT."targetShape"[8] ->> 'target-finalRotationX') :: numeric(3, 2)        "task8_target-finalRotationX",
(AT."targetShape"[8] ->> 'target-finalRotationY') :: numeric(3, 2)        "task8_target-finalRotationY",
(AT."targetShape"[8] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task8_target-finalRotationZ",
(AT."targetShape"[8] ->> 'target-maxDeltaForNextBlock') :: integer        "task8_target-maxDeltaForNextBlock",
(AT."images"[8] ->> 'scene') :: text                                      "task8_img-scene",
(AT."images"[8] ->> 'testShape') :: text                                  "task8_img-testShape",
(AT."images"[8] ->> 'testShape1') :: text                                 "task8_img-testShape1",
(AT."images"[8] ->> 'testShape2') :: text                                 "task8_img-testShape2",
(AT."images"[8] ->> 'testShape3') :: text                                 "task8_img-testShape3",
(AT."images"[8] ->> 'testShape4') :: text                                 "task8_img-testShape4",
(AT."images"[8] ->> 'testShape5') :: text                                 "task8_img-testShape5",
(AT."images"[8] ->> 'referenceShape') :: text                             "task8_img-referenceShape",
(AT."images"[8] ->> 'referenceShapeRotated') :: text                      "task8_img-referenceShapeRotated",
AT."correctAnswer"[8]                                                     "task8_correctAnswer",

--     task 9
(AT.angles[9] ->> 'rotationX'):: integer                                  "task9_rotationX",
(AT.angles[9] ->> 'rotationY'):: integer                                  "task9_rotationY",
(AT.angles[9] ->> 'rotationZ'):: integer                                  "task9_rotationZ",
(AT."referenceShape"[9] ->> 'reference-spreadOnX') :: numeric(3, 2)       "task9_reference-spreadOnX",
(AT."referenceShape"[9] ->> 'reference-spreadOnY') :: numeric(3, 2)       "task9_reference-spreadOnY",
(AT."referenceShape"[9] ->> 'reference-spreadOnZ') :: numeric(3, 2)       "task9_reference-spreadOnZ",
(AT."referenceShape"[9] ->> 'reference-totalBlocks') :: integer           "task9_reference-totalBlocks",
(AT."referenceShape"[9] ->> 'reference-finalRotationX') :: numeric(3, 2)  "task9_reference-finalRotationX",
(AT."referenceShape"[9] ->> 'reference-finalRotationY') :: numeric(3, 2)  "task9_reference-finalRotationY",
(AT."referenceShape"[9] ->> 'reference-finalRotationZ') :: numeric(3, 2)  "task9_reference-finalRotationZ",
(AT."referenceShape"[9] ->> 'reference-maxDeltaForNextBlock') :: integer  "task9_reference-maxDeltaForNextBlock",
(AT."targetShape"[9] ->> 'target-spreadOnX') :: numeric(3, 2)             "task9_target-spreadOnX",
(AT."targetShape"[9] ->> 'target-spreadOnY') :: numeric(3, 2)             "task9_target-spreadOnY",
(AT."targetShape"[9] ->> 'target-spreadOnZ') :: numeric(3, 2)             "task9_target-spreadOnZ",
(AT."targetShape"[9] ->> 'target-totalBlocks') :: integer                 "task9_target-totalBlocks",
(AT."targetShape"[9] ->> 'target-finalRotationX') :: numeric(3, 2)        "task9_target-finalRotationX",
(AT."targetShape"[9] ->> 'target-finalRotationY') :: numeric(3, 2)        "task9_target-finalRotationY",
(AT."targetShape"[9] ->> 'target-finalRotationZ') :: numeric(3, 2)        "task9_target-finalRotationZ",
(AT."targetShape"[9] ->> 'target-maxDeltaForNextBlock') :: integer        "task9_target-maxDeltaForNextBlock",
(AT."images"[9] ->> 'scene') :: text                                      "task9_img-scene",
(AT."images"[9] ->> 'testShape') :: text                                  "task9_img-testShape",
(AT."images"[9] ->> 'testShape1') :: text                                 "task9_img-testShape1",
(AT."images"[9] ->> 'testShape2') :: text                                 "task9_img-testShape2",
(AT."images"[9] ->> 'testShape3') :: text                                 "task9_img-testShape3",
(AT."images"[9] ->> 'testShape4') :: text                                 "task9_img-testShape4",
(AT."images"[9] ->> 'testShape5') :: text                                 "task9_img-testShape5",
(AT."images"[9] ->> 'referenceShape') :: text                             "task9_img-referenceShape",
(AT."images"[9] ->> 'referenceShapeRotated') :: text                      "task9_img-referenceShapeRotated",
AT."correctAnswer"[9]                                                     "task9_correctAnswer",

--     task 10
(AT.angles[10] ->> 'rotationX'):: integer                                 "task10_rotationX",
(AT.angles[10] ->> 'rotationY'):: integer                                 "task10_rotationY",
(AT.angles[10] ->> 'rotationZ'):: integer                                 "task10_rotationZ",
(AT."referenceShape"[10] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task10_reference-spreadOnX",
(AT."referenceShape"[10] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task10_reference-spreadOnY",
(AT."referenceShape"[10] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task10_reference-spreadOnZ",
(AT."referenceShape"[10] ->> 'reference-totalBlocks') :: integer          "task10_reference-totalBlocks",
(AT."referenceShape"[10] ->> 'reference-finalRotationX') :: numeric(3, 2) "task10_reference-finalRotationX",
(AT."referenceShape"[10] ->> 'reference-finalRotationY') :: numeric(3, 2) "task10_reference-finalRotationY",
(AT."referenceShape"[10] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task10_reference-finalRotationZ",
(AT."referenceShape"[10] ->> 'reference-maxDeltaForNextBlock') :: integer "task10_reference-maxDeltaForNextBlock",
(AT."targetShape"[10] ->> 'target-spreadOnX') :: numeric(3, 2)            "task10_target-spreadOnX",
(AT."targetShape"[10] ->> 'target-spreadOnY') :: numeric(3, 2)            "task10_target-spreadOnY",
(AT."targetShape"[10] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task10_target-spreadOnZ",
(AT."targetShape"[10] ->> 'target-totalBlocks') :: integer                "task10_target-totalBlocks",
(AT."targetShape"[10] ->> 'target-finalRotationX') :: numeric(3, 2)       "task10_target-finalRotationX",
(AT."targetShape"[10] ->> 'target-finalRotationY') :: numeric(3, 2)       "task10_target-finalRotationY",
(AT."targetShape"[10] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task10_target-finalRotationZ",
(AT."targetShape"[10] ->> 'target-maxDeltaForNextBlock') :: integer       "task10_target-maxDeltaForNextBlock",
(AT."images"[10] ->> 'scene') :: text                                     "task10_img-scene",
(AT."images"[10] ->> 'testShape') :: text                                 "task10_img-testShape",
(AT."images"[10] ->> 'testShape1') :: text                                "task10_img-testShape1",
(AT."images"[10] ->> 'testShape2') :: text                                "task10_img-testShape2",
(AT."images"[10] ->> 'testShape3') :: text                                "task10_img-testShape3",
(AT."images"[10] ->> 'testShape4') :: text                                "task10_img-testShape4",
(AT."images"[10] ->> 'testShape5') :: text                                "task10_img-testShape5",
(AT."images"[10] ->> 'referenceShape') :: text                            "task10_img-referenceShape",
(AT."images"[10] ->> 'referenceShapeRotated') :: text                     "task10_img-referenceShapeRotated",
AT."correctAnswer"[10]                                                    "task10_correctAnswer",

--     task 11
(AT.angles[11] ->> 'rotationX'):: integer                                 "task11_rotationX",
(AT.angles[11] ->> 'rotationY'):: integer                                 "task11_rotationY",
(AT.angles[11] ->> 'rotationZ'):: integer                                 "task11_rotationZ",
(AT."referenceShape"[11] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task11_reference-spreadOnX",
(AT."referenceShape"[11] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task11_reference-spreadOnY",
(AT."referenceShape"[11] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task11_reference-spreadOnZ",
(AT."referenceShape"[11] ->> 'reference-totalBlocks') :: integer          "task11_reference-totalBlocks",
(AT."referenceShape"[11] ->> 'reference-finalRotationX') :: numeric(3, 2) "task11_reference-finalRotationX",
(AT."referenceShape"[11] ->> 'reference-finalRotationY') :: numeric(3, 2) "task11_reference-finalRotationY",
(AT."referenceShape"[11] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task11_reference-finalRotationZ",
(AT."referenceShape"[11] ->> 'reference-maxDeltaForNextBlock') :: integer "task11_reference-maxDeltaForNextBlock",
(AT."targetShape"[11] ->> 'target-spreadOnX') :: numeric(3, 2)            "task11_target-spreadOnX",
(AT."targetShape"[11] ->> 'target-spreadOnY') :: numeric(3, 2)            "task11_target-spreadOnY",
(AT."targetShape"[11] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task11_target-spreadOnZ",
(AT."targetShape"[11] ->> 'target-totalBlocks') :: integer                "task11_target-totalBlocks",
(AT."targetShape"[11] ->> 'target-finalRotationX') :: numeric(3, 2)       "task11_target-finalRotationX",
(AT."targetShape"[11] ->> 'target-finalRotationY') :: numeric(3, 2)       "task11_target-finalRotationY",
(AT."targetShape"[11] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task11_target-finalRotationZ",
(AT."targetShape"[11] ->> 'target-maxDeltaForNextBlock') :: integer       "task11_target-maxDeltaForNextBlock",
(AT."images"[11] ->> 'scene') :: text                                     "task11_img-scene",
(AT."images"[11] ->> 'testShape') :: text                                 "task11_img-testShape",
(AT."images"[11] ->> 'testShape1') :: text                                "task11_img-testShape1",
(AT."images"[11] ->> 'testShape2') :: text                                "task11_img-testShape2",
(AT."images"[11] ->> 'testShape3') :: text                                "task11_img-testShape3",
(AT."images"[11] ->> 'testShape4') :: text                                "task11_img-testShape4",
(AT."images"[11] ->> 'testShape5') :: text                                "task11_img-testShape5",
(AT."images"[11] ->> 'referenceShape') :: text                            "task11_img-referenceShape",
(AT."images"[11] ->> 'referenceShapeRotated') :: text                     "task11_img-referenceShapeRotated",
AT."correctAnswer"[11]                                                    "task11_correctAnswer",

--     task 12
(AT.angles[12] ->> 'rotationX'):: integer                                 "task12_rotationX",
(AT.angles[12] ->> 'rotationY'):: integer                                 "task12_rotationY",
(AT.angles[12] ->> 'rotationZ'):: integer                                 "task12_rotationZ",
(AT."referenceShape"[12] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task12_reference-spreadOnX",
(AT."referenceShape"[12] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task12_reference-spreadOnY",
(AT."referenceShape"[12] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task12_reference-spreadOnZ",
(AT."referenceShape"[12] ->> 'reference-totalBlocks') :: integer          "task12_reference-totalBlocks",
(AT."referenceShape"[12] ->> 'reference-finalRotationX') :: numeric(3, 2) "task12_reference-finalRotationX",
(AT."referenceShape"[12] ->> 'reference-finalRotationY') :: numeric(3, 2) "task12_reference-finalRotationY",
(AT."referenceShape"[12] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task12_reference-finalRotationZ",
(AT."referenceShape"[12] ->> 'reference-maxDeltaForNextBlock') :: integer "task12_reference-maxDeltaForNextBlock",
(AT."targetShape"[12] ->> 'target-spreadOnX') :: numeric(3, 2)            "task12_target-spreadOnX",
(AT."targetShape"[12] ->> 'target-spreadOnY') :: numeric(3, 2)            "task12_target-spreadOnY",
(AT."targetShape"[12] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task12_target-spreadOnZ",
(AT."targetShape"[12] ->> 'target-totalBlocks') :: integer                "task12_target-totalBlocks",
(AT."targetShape"[12] ->> 'target-finalRotationX') :: numeric(3, 2)       "task12_target-finalRotationX",
(AT."targetShape"[12] ->> 'target-finalRotationY') :: numeric(3, 2)       "task12_target-finalRotationY",
(AT."targetShape"[12] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task12_target-finalRotationZ",
(AT."targetShape"[12] ->> 'target-maxDeltaForNextBlock') :: integer       "task12_target-maxDeltaForNextBlock",
(AT."images"[12] ->> 'scene') :: text                                     "task12_img-scene",
(AT."images"[12] ->> 'testShape') :: text                                 "task12_img-testShape",
(AT."images"[12] ->> 'testShape1') :: text                                "task12_img-testShape1",
(AT."images"[12] ->> 'testShape2') :: text                                "task12_img-testShape2",
(AT."images"[12] ->> 'testShape3') :: text                                "task12_img-testShape3",
(AT."images"[12] ->> 'testShape4') :: text                                "task12_img-testShape4",
(AT."images"[12] ->> 'testShape5') :: text                                "task12_img-testShape5",
(AT."images"[12] ->> 'referenceShape') :: text                            "task12_img-referenceShape",
(AT."images"[12] ->> 'referenceShapeRotated') :: text                     "task12_img-referenceShapeRotated",
AT."correctAnswer"[12]                                                    "task12_correctAnswer",

--     task 13
(AT.angles[13] ->> 'rotationX'):: integer                                 "task13_rotationX",
(AT.angles[13] ->> 'rotationY'):: integer                                 "task13_rotationY",
(AT.angles[13] ->> 'rotationZ'):: integer                                 "task13_rotationZ",
(AT."referenceShape"[13] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task13_reference-spreadOnX",
(AT."referenceShape"[13] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task13_reference-spreadOnY",
(AT."referenceShape"[13] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task13_reference-spreadOnZ",
(AT."referenceShape"[13] ->> 'reference-totalBlocks') :: integer          "task13_reference-totalBlocks",
(AT."referenceShape"[13] ->> 'reference-finalRotationX') :: numeric(3, 2) "task13_reference-finalRotationX",
(AT."referenceShape"[13] ->> 'reference-finalRotationY') :: numeric(3, 2) "task13_reference-finalRotationY",
(AT."referenceShape"[13] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task13_reference-finalRotationZ",
(AT."referenceShape"[13] ->> 'reference-maxDeltaForNextBlock') :: integer "task13_reference-maxDeltaForNextBlock",
(AT."targetShape"[13] ->> 'target-spreadOnX') :: numeric(3, 2)            "task13_target-spreadOnX",
(AT."targetShape"[13] ->> 'target-spreadOnY') :: numeric(3, 2)            "task13_target-spreadOnY",
(AT."targetShape"[13] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task13_target-spreadOnZ",
(AT."targetShape"[13] ->> 'target-totalBlocks') :: integer                "task13_target-totalBlocks",
(AT."targetShape"[13] ->> 'target-finalRotationX') :: numeric(3, 2)       "task13_target-finalRotationX",
(AT."targetShape"[13] ->> 'target-finalRotationY') :: numeric(3, 2)       "task13_target-finalRotationY",
(AT."targetShape"[13] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task13_target-finalRotationZ",
(AT."targetShape"[13] ->> 'target-maxDeltaForNextBlock') :: integer       "task13_target-maxDeltaForNextBlock",
(AT."images"[13] ->> 'scene') :: text                                     "task13_img-scene",
(AT."images"[13] ->> 'testShape') :: text                                 "task13_img-testShape",
(AT."images"[13] ->> 'testShape1') :: text                                "task13_img-testShape1",
(AT."images"[13] ->> 'testShape2') :: text                                "task13_img-testShape2",
(AT."images"[13] ->> 'testShape3') :: text                                "task13_img-testShape3",
(AT."images"[13] ->> 'testShape4') :: text                                "task13_img-testShape4",
(AT."images"[13] ->> 'testShape5') :: text                                "task13_img-testShape5",
(AT."images"[13] ->> 'referenceShape') :: text                            "task13_img-referenceShape",
(AT."images"[13] ->> 'referenceShapeRotated') :: text                     "task13_img-referenceShapeRotated",
AT."correctAnswer"[13]                                                    "task13_correctAnswer",

--     task 14
(AT.angles[14] ->> 'rotationX'):: integer                                 "task14_rotationX",
(AT.angles[14] ->> 'rotationY'):: integer                                 "task14_rotationY",
(AT.angles[14] ->> 'rotationZ'):: integer                                 "task14_rotationZ",
(AT."referenceShape"[14] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task14_reference-spreadOnX",
(AT."referenceShape"[14] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task14_reference-spreadOnY",
(AT."referenceShape"[14] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task14_reference-spreadOnZ",
(AT."referenceShape"[14] ->> 'reference-totalBlocks') :: integer          "task14_reference-totalBlocks",
(AT."referenceShape"[14] ->> 'reference-finalRotationX') :: numeric(3, 2) "task14_reference-finalRotationX",
(AT."referenceShape"[14] ->> 'reference-finalRotationY') :: numeric(3, 2) "task14_reference-finalRotationY",
(AT."referenceShape"[14] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task14_reference-finalRotationZ",
(AT."referenceShape"[14] ->> 'reference-maxDeltaForNextBlock') :: integer "task14_reference-maxDeltaForNextBlock",
(AT."targetShape"[14] ->> 'target-spreadOnX') :: numeric(3, 2)            "task14_target-spreadOnX",
(AT."targetShape"[14] ->> 'target-spreadOnY') :: numeric(3, 2)            "task14_target-spreadOnY",
(AT."targetShape"[14] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task14_target-spreadOnZ",
(AT."targetShape"[14] ->> 'target-totalBlocks') :: integer                "task14_target-totalBlocks",
(AT."targetShape"[14] ->> 'target-finalRotationX') :: numeric(3, 2)       "task14_target-finalRotationX",
(AT."targetShape"[14] ->> 'target-finalRotationY') :: numeric(3, 2)       "task14_target-finalRotationY",
(AT."targetShape"[14] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task14_target-finalRotationZ",
(AT."targetShape"[14] ->> 'target-maxDeltaForNextBlock') :: integer       "task14_target-maxDeltaForNextBlock",
(AT."images"[14] ->> 'scene') :: text                                     "task14_img-scene",
(AT."images"[14] ->> 'testShape') :: text                                 "task14_img-testShape",
(AT."images"[14] ->> 'testShape1') :: text                                "task14_img-testShape1",
(AT."images"[14] ->> 'testShape2') :: text                                "task14_img-testShape2",
(AT."images"[14] ->> 'testShape3') :: text                                "task14_img-testShape3",
(AT."images"[14] ->> 'testShape4') :: text                                "task14_img-testShape4",
(AT."images"[14] ->> 'testShape5') :: text                                "task14_img-testShape5",
(AT."images"[14] ->> 'referenceShape') :: text                            "task14_img-referenceShape",
(AT."images"[14] ->> 'referenceShapeRotated') :: text                     "task14_img-referenceShapeRotated",
AT."correctAnswer"[14]                                                    "task14_correctAnswer",

--     task 15
(AT.angles[15] ->> 'rotationX'):: integer                                 "task15_rotationX",
(AT.angles[15] ->> 'rotationY'):: integer                                 "task15_rotationY",
(AT.angles[15] ->> 'rotationZ'):: integer                                 "task15_rotationZ",
(AT."referenceShape"[15] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task15_reference-spreadOnX",
(AT."referenceShape"[15] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task15_reference-spreadOnY",
(AT."referenceShape"[15] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task15_reference-spreadOnZ",
(AT."referenceShape"[15] ->> 'reference-totalBlocks') :: integer          "task15_reference-totalBlocks",
(AT."referenceShape"[15] ->> 'reference-finalRotationX') :: numeric(3, 2) "task15_reference-finalRotationX",
(AT."referenceShape"[15] ->> 'reference-finalRotationY') :: numeric(3, 2) "task15_reference-finalRotationY",
(AT."referenceShape"[15] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task15_reference-finalRotationZ",
(AT."referenceShape"[15] ->> 'reference-maxDeltaForNextBlock') :: integer "task15_reference-maxDeltaForNextBlock",
(AT."targetShape"[15] ->> 'target-spreadOnX') :: numeric(3, 2)            "task15_target-spreadOnX",
(AT."targetShape"[15] ->> 'target-spreadOnY') :: numeric(3, 2)            "task15_target-spreadOnY",
(AT."targetShape"[15] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task15_target-spreadOnZ",
(AT."targetShape"[15] ->> 'target-totalBlocks') :: integer                "task15_target-totalBlocks",
(AT."targetShape"[15] ->> 'target-finalRotationX') :: numeric(3, 2)       "task15_target-finalRotationX",
(AT."targetShape"[15] ->> 'target-finalRotationY') :: numeric(3, 2)       "task15_target-finalRotationY",
(AT."targetShape"[15] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task15_target-finalRotationZ",
(AT."targetShape"[15] ->> 'target-maxDeltaForNextBlock') :: integer       "task15_target-maxDeltaForNextBlock",
(AT."images"[15] ->> 'scene') :: text                                     "task15_img-scene",
(AT."images"[15] ->> 'testShape') :: text                                 "task15_img-testShape",
(AT."images"[15] ->> 'testShape1') :: text                                "task15_img-testShape1",
(AT."images"[15] ->> 'testShape2') :: text                                "task15_img-testShape2",
(AT."images"[15] ->> 'testShape3') :: text                                "task15_img-testShape3",
(AT."images"[15] ->> 'testShape4') :: text                                "task15_img-testShape4",
(AT."images"[15] ->> 'testShape5') :: text                                "task15_img-testShape5",
(AT."images"[15] ->> 'referenceShape') :: text                            "task15_img-referenceShape",
(AT."images"[15] ->> 'referenceShapeRotated') :: text                     "task15_img-referenceShapeRotated",
AT."correctAnswer"[15]                                                    "task15_correctAnswer",

--     task 16
(AT.angles[16] ->> 'rotationX'):: integer                                 "task16_rotationX",
(AT.angles[16] ->> 'rotationY'):: integer                                 "task16_rotationY",
(AT.angles[16] ->> 'rotationZ'):: integer                                 "task16_rotationZ",
(AT."referenceShape"[16] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task16_reference-spreadOnX",
(AT."referenceShape"[16] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task16_reference-spreadOnY",
(AT."referenceShape"[16] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task16_reference-spreadOnZ",
(AT."referenceShape"[16] ->> 'reference-totalBlocks') :: integer          "task16_reference-totalBlocks",
(AT."referenceShape"[16] ->> 'reference-finalRotationX') :: numeric(3, 2) "task16_reference-finalRotationX",
(AT."referenceShape"[16] ->> 'reference-finalRotationY') :: numeric(3, 2) "task16_reference-finalRotationY",
(AT."referenceShape"[16] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task16_reference-finalRotationZ",
(AT."referenceShape"[16] ->> 'reference-maxDeltaForNextBlock') :: integer "task16_reference-maxDeltaForNextBlock",
(AT."targetShape"[16] ->> 'target-spreadOnX') :: numeric(3, 2)            "task16_target-spreadOnX",
(AT."targetShape"[16] ->> 'target-spreadOnY') :: numeric(3, 2)            "task16_target-spreadOnY",
(AT."targetShape"[16] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task16_target-spreadOnZ",
(AT."targetShape"[16] ->> 'target-totalBlocks') :: integer                "task16_target-totalBlocks",
(AT."targetShape"[16] ->> 'target-finalRotationX') :: numeric(3, 2)       "task16_target-finalRotationX",
(AT."targetShape"[16] ->> 'target-finalRotationY') :: numeric(3, 2)       "task16_target-finalRotationY",
(AT."targetShape"[16] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task16_target-finalRotationZ",
(AT."targetShape"[16] ->> 'target-maxDeltaForNextBlock') :: integer       "task16_target-maxDeltaForNextBlock",
(AT."images"[16] ->> 'scene') :: text                                     "task16_img-scene",
(AT."images"[16] ->> 'testShape') :: text                                 "task16_img-testShape",
(AT."images"[16] ->> 'testShape1') :: text                                "task16_img-testShape1",
(AT."images"[16] ->> 'testShape2') :: text                                "task16_img-testShape2",
(AT."images"[16] ->> 'testShape3') :: text                                "task16_img-testShape3",
(AT."images"[16] ->> 'testShape4') :: text                                "task16_img-testShape4",
(AT."images"[16] ->> 'testShape5') :: text                                "task16_img-testShape5",
(AT."images"[16] ->> 'referenceShape') :: text                            "task16_img-referenceShape",
(AT."images"[16] ->> 'referenceShapeRotated') :: text                     "task16_img-referenceShapeRotated",
AT."correctAnswer"[16]                                                    "task16_correctAnswer",

--     task 17
(AT.angles[17] ->> 'rotationX'):: integer                                 "task17_rotationX",
(AT.angles[17] ->> 'rotationY'):: integer                                 "task17_rotationY",
(AT.angles[17] ->> 'rotationZ'):: integer                                 "task17_rotationZ",
(AT."referenceShape"[17] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task17_reference-spreadOnX",
(AT."referenceShape"[17] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task17_reference-spreadOnY",
(AT."referenceShape"[17] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task17_reference-spreadOnZ",
(AT."referenceShape"[17] ->> 'reference-totalBlocks') :: integer          "task17_reference-totalBlocks",
(AT."referenceShape"[17] ->> 'reference-finalRotationX') :: numeric(3, 2) "task17_reference-finalRotationX",
(AT."referenceShape"[17] ->> 'reference-finalRotationY') :: numeric(3, 2) "task17_reference-finalRotationY",
(AT."referenceShape"[17] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task17_reference-finalRotationZ",
(AT."referenceShape"[17] ->> 'reference-maxDeltaForNextBlock') :: integer "task17_reference-maxDeltaForNextBlock",
(AT."targetShape"[17] ->> 'target-spreadOnX') :: numeric(3, 2)            "task17_target-spreadOnX",
(AT."targetShape"[17] ->> 'target-spreadOnY') :: numeric(3, 2)            "task17_target-spreadOnY",
(AT."targetShape"[17] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task17_target-spreadOnZ",
(AT."targetShape"[17] ->> 'target-totalBlocks') :: integer                "task17_target-totalBlocks",
(AT."targetShape"[17] ->> 'target-finalRotationX') :: numeric(3, 2)       "task17_target-finalRotationX",
(AT."targetShape"[17] ->> 'target-finalRotationY') :: numeric(3, 2)       "task17_target-finalRotationY",
(AT."targetShape"[17] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task17_target-finalRotationZ",
(AT."targetShape"[17] ->> 'target-maxDeltaForNextBlock') :: integer       "task17_target-maxDeltaForNextBlock",
(AT."images"[17] ->> 'scene') :: text                                     "task17_img-scene",
(AT."images"[17] ->> 'testShape') :: text                                 "task17_img-testShape",
(AT."images"[17] ->> 'testShape1') :: text                                "task17_img-testShape1",
(AT."images"[17] ->> 'testShape2') :: text                                "task17_img-testShape2",
(AT."images"[17] ->> 'testShape3') :: text                                "task17_img-testShape3",
(AT."images"[17] ->> 'testShape4') :: text                                "task17_img-testShape4",
(AT."images"[17] ->> 'testShape5') :: text                                "task17_img-testShape5",
(AT."images"[17] ->> 'referenceShape') :: text                            "task17_img-referenceShape",
(AT."images"[17] ->> 'referenceShapeRotated') :: text                     "task17_img-referenceShapeRotated",
AT."correctAnswer"[17]                                                    "task17_correctAnswer",

--     task 18
(AT.angles[18] ->> 'rotationX'):: integer                                 "task18_rotationX",
(AT.angles[18] ->> 'rotationY'):: integer                                 "task18_rotationY",
(AT.angles[18] ->> 'rotationZ'):: integer                                 "task18_rotationZ",
(AT."referenceShape"[18] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task18_reference-spreadOnX",
(AT."referenceShape"[18] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task18_reference-spreadOnY",
(AT."referenceShape"[18] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task18_reference-spreadOnZ",
(AT."referenceShape"[18] ->> 'reference-totalBlocks') :: integer          "task18_reference-totalBlocks",
(AT."referenceShape"[18] ->> 'reference-finalRotationX') :: numeric(3, 2) "task18_reference-finalRotationX",
(AT."referenceShape"[18] ->> 'reference-finalRotationY') :: numeric(3, 2) "task18_reference-finalRotationY",
(AT."referenceShape"[18] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task18_reference-finalRotationZ",
(AT."referenceShape"[18] ->> 'reference-maxDeltaForNextBlock') :: integer "task18_reference-maxDeltaForNextBlock",
(AT."targetShape"[18] ->> 'target-spreadOnX') :: numeric(3, 2)            "task18_target-spreadOnX",
(AT."targetShape"[18] ->> 'target-spreadOnY') :: numeric(3, 2)            "task18_target-spreadOnY",
(AT."targetShape"[18] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task18_target-spreadOnZ",
(AT."targetShape"[18] ->> 'target-totalBlocks') :: integer                "task18_target-totalBlocks",
(AT."targetShape"[18] ->> 'target-finalRotationX') :: numeric(3, 2)       "task18_target-finalRotationX",
(AT."targetShape"[18] ->> 'target-finalRotationY') :: numeric(3, 2)       "task18_target-finalRotationY",
(AT."targetShape"[18] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task18_target-finalRotationZ",
(AT."targetShape"[18] ->> 'target-maxDeltaForNextBlock') :: integer       "task18_target-maxDeltaForNextBlock",
(AT."images"[18] ->> 'scene') :: text                                     "task18_img-scene",
(AT."images"[18] ->> 'testShape') :: text                                 "task18_img-testShape",
(AT."images"[18] ->> 'testShape1') :: text                                "task18_img-testShape1",
(AT."images"[18] ->> 'testShape2') :: text                                "task18_img-testShape2",
(AT."images"[18] ->> 'testShape3') :: text                                "task18_img-testShape3",
(AT."images"[18] ->> 'testShape4') :: text                                "task18_img-testShape4",
(AT."images"[18] ->> 'testShape5') :: text                                "task18_img-testShape5",
(AT."images"[18] ->> 'referenceShape') :: text                            "task18_img-referenceShape",
(AT."images"[18] ->> 'referenceShapeRotated') :: text                     "task18_img-referenceShapeRotated",
AT."correctAnswer"[18]                                                    "task18_correctAnswer",

--     task 19
(AT.angles[19] ->> 'rotationX'):: integer                                 "task19_rotationX",
(AT.angles[19] ->> 'rotationY'):: integer                                 "task19_rotationY",
(AT.angles[19] ->> 'rotationZ'):: integer                                 "task19_rotationZ",
(AT."referenceShape"[19] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task19_reference-spreadOnX",
(AT."referenceShape"[19] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task19_reference-spreadOnY",
(AT."referenceShape"[19] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task19_reference-spreadOnZ",
(AT."referenceShape"[19] ->> 'reference-totalBlocks') :: integer          "task19_reference-totalBlocks",
(AT."referenceShape"[19] ->> 'reference-finalRotationX') :: numeric(3, 2) "task19_reference-finalRotationX",
(AT."referenceShape"[19] ->> 'reference-finalRotationY') :: numeric(3, 2) "task19_reference-finalRotationY",
(AT."referenceShape"[19] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task19_reference-finalRotationZ",
(AT."referenceShape"[19] ->> 'reference-maxDeltaForNextBlock') :: integer "task19_reference-maxDeltaForNextBlock",
(AT."targetShape"[19] ->> 'target-spreadOnX') :: numeric(3, 2)            "task19_target-spreadOnX",
(AT."targetShape"[19] ->> 'target-spreadOnY') :: numeric(3, 2)            "task19_target-spreadOnY",
(AT."targetShape"[19] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task19_target-spreadOnZ",
(AT."targetShape"[19] ->> 'target-totalBlocks') :: integer                "task19_target-totalBlocks",
(AT."targetShape"[19] ->> 'target-finalRotationX') :: numeric(3, 2)       "task19_target-finalRotationX",
(AT."targetShape"[19] ->> 'target-finalRotationY') :: numeric(3, 2)       "task19_target-finalRotationY",
(AT."targetShape"[19] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task19_target-finalRotationZ",
(AT."targetShape"[19] ->> 'target-maxDeltaForNextBlock') :: integer       "task19_target-maxDeltaForNextBlock",
(AT."images"[19] ->> 'scene') :: text                                     "task19_img-scene",
(AT."images"[19] ->> 'testShape') :: text                                 "task19_img-testShape",
(AT."images"[19] ->> 'testShape1') :: text                                "task19_img-testShape1",
(AT."images"[19] ->> 'testShape2') :: text                                "task19_img-testShape2",
(AT."images"[19] ->> 'testShape3') :: text                                "task19_img-testShape3",
(AT."images"[19] ->> 'testShape4') :: text                                "task19_img-testShape4",
(AT."images"[19] ->> 'testShape5') :: text                                "task19_img-testShape5",
(AT."images"[19] ->> 'referenceShape') :: text                            "task19_img-referenceShape",
(AT."images"[19] ->> 'referenceShapeRotated') :: text                     "task19_img-referenceShapeRotated",
AT."correctAnswer"[19]                                                    "task19_correctAnswer",

--     task 20
(AT.angles[20] ->> 'rotationX'):: integer                                 "task20_rotationX",
(AT.angles[20] ->> 'rotationY'):: integer                                 "task20_rotationY",
(AT.angles[20] ->> 'rotationZ'):: integer                                 "task20_rotationZ",
(AT."referenceShape"[20] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task20_reference-spreadOnX",
(AT."referenceShape"[20] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task20_reference-spreadOnY",
(AT."referenceShape"[20] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task20_reference-spreadOnZ",
(AT."referenceShape"[20] ->> 'reference-totalBlocks') :: integer          "task20_reference-totalBlocks",
(AT."referenceShape"[20] ->> 'reference-finalRotationX') :: numeric(3, 2) "task20_reference-finalRotationX",
(AT."referenceShape"[20] ->> 'reference-finalRotationY') :: numeric(3, 2) "task20_reference-finalRotationY",
(AT."referenceShape"[20] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task20_reference-finalRotationZ",
(AT."referenceShape"[20] ->> 'reference-maxDeltaForNextBlock') :: integer "task20_reference-maxDeltaForNextBlock",
(AT."targetShape"[20] ->> 'target-spreadOnX') :: numeric(3, 2)            "task20_target-spreadOnX",
(AT."targetShape"[20] ->> 'target-spreadOnY') :: numeric(3, 2)            "task20_target-spreadOnY",
(AT."targetShape"[20] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task20_target-spreadOnZ",
(AT."targetShape"[20] ->> 'target-totalBlocks') :: integer                "task20_target-totalBlocks",
(AT."targetShape"[20] ->> 'target-finalRotationX') :: numeric(3, 2)       "task20_target-finalRotationX",
(AT."targetShape"[20] ->> 'target-finalRotationY') :: numeric(3, 2)       "task20_target-finalRotationY",
(AT."targetShape"[20] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task20_target-finalRotationZ",
(AT."targetShape"[20] ->> 'target-maxDeltaForNextBlock') :: integer       "task20_target-maxDeltaForNextBlock",
(AT."images"[20] ->> 'scene') :: text                                     "task20_img-scene",
(AT."images"[20] ->> 'testShape') :: text                                 "task20_img-testShape",
(AT."images"[20] ->> 'testShape1') :: text                                "task20_img-testShape1",
(AT."images"[20] ->> 'testShape2') :: text                                "task20_img-testShape2",
(AT."images"[20] ->> 'testShape3') :: text                                "task20_img-testShape3",
(AT."images"[20] ->> 'testShape4') :: text                                "task20_img-testShape4",
(AT."images"[20] ->> 'testShape5') :: text                                "task20_img-testShape5",
(AT."images"[20] ->> 'referenceShape') :: text                            "task20_img-referenceShape",
(AT."images"[20] ->> 'referenceShapeRotated') :: text                     "task20_img-referenceShapeRotated",
AT."correctAnswer"[20]                                                    "task20_correctAnswer",

--     task 21
(AT.angles[21] ->> 'rotationX'):: integer                                 "task21_rotationX",
(AT.angles[21] ->> 'rotationY'):: integer                                 "task21_rotationY",
(AT.angles[21] ->> 'rotationZ'):: integer                                 "task21_rotationZ",
(AT."referenceShape"[21] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task21_reference-spreadOnX",
(AT."referenceShape"[21] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task21_reference-spreadOnY",
(AT."referenceShape"[21] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task21_reference-spreadOnZ",
(AT."referenceShape"[21] ->> 'reference-totalBlocks') :: integer          "task21_reference-totalBlocks",
(AT."referenceShape"[21] ->> 'reference-finalRotationX') :: numeric(3, 2) "task21_reference-finalRotationX",
(AT."referenceShape"[21] ->> 'reference-finalRotationY') :: numeric(3, 2) "task21_reference-finalRotationY",
(AT."referenceShape"[21] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task21_reference-finalRotationZ",
(AT."referenceShape"[21] ->> 'reference-maxDeltaForNextBlock') :: integer "task21_reference-maxDeltaForNextBlock",
(AT."targetShape"[21] ->> 'target-spreadOnX') :: numeric(3, 2)            "task21_target-spreadOnX",
(AT."targetShape"[21] ->> 'target-spreadOnY') :: numeric(3, 2)            "task21_target-spreadOnY",
(AT."targetShape"[21] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task21_target-spreadOnZ",
(AT."targetShape"[21] ->> 'target-totalBlocks') :: integer                "task21_target-totalBlocks",
(AT."targetShape"[21] ->> 'target-finalRotationX') :: numeric(3, 2)       "task21_target-finalRotationX",
(AT."targetShape"[21] ->> 'target-finalRotationY') :: numeric(3, 2)       "task21_target-finalRotationY",
(AT."targetShape"[21] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task21_target-finalRotationZ",
(AT."targetShape"[21] ->> 'target-maxDeltaForNextBlock') :: integer       "task21_target-maxDeltaForNextBlock",
(AT."images"[21] ->> 'scene') :: text                                     "task21_img-scene",
(AT."images"[21] ->> 'testShape') :: text                                 "task21_img-testShape",
(AT."images"[21] ->> 'testShape1') :: text                                "task21_img-testShape1",
(AT."images"[21] ->> 'testShape2') :: text                                "task21_img-testShape2",
(AT."images"[21] ->> 'testShape3') :: text                                "task21_img-testShape3",
(AT."images"[21] ->> 'testShape4') :: text                                "task21_img-testShape4",
(AT."images"[21] ->> 'testShape5') :: text                                "task21_img-testShape5",
(AT."images"[21] ->> 'referenceShape') :: text                            "task21_img-referenceShape",
(AT."images"[21] ->> 'referenceShapeRotated') :: text                     "task21_img-referenceShapeRotated",
AT."correctAnswer"[21]                                                    "task21_correctAnswer",

--     task 22
(AT.angles[22] ->> 'rotationX'):: integer                                 "task22_rotationX",
(AT.angles[22] ->> 'rotationY'):: integer                                 "task22_rotationY",
(AT.angles[22] ->> 'rotationZ'):: integer                                 "task22_rotationZ",
(AT."referenceShape"[22] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task22_reference-spreadOnX",
(AT."referenceShape"[22] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task22_reference-spreadOnY",
(AT."referenceShape"[22] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task22_reference-spreadOnZ",
(AT."referenceShape"[22] ->> 'reference-totalBlocks') :: integer          "task22_reference-totalBlocks",
(AT."referenceShape"[22] ->> 'reference-finalRotationX') :: numeric(3, 2) "task22_reference-finalRotationX",
(AT."referenceShape"[22] ->> 'reference-finalRotationY') :: numeric(3, 2) "task22_reference-finalRotationY",
(AT."referenceShape"[22] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task22_reference-finalRotationZ",
(AT."referenceShape"[22] ->> 'reference-maxDeltaForNextBlock') :: integer "task22_reference-maxDeltaForNextBlock",
(AT."targetShape"[22] ->> 'target-spreadOnX') :: numeric(3, 2)            "task22_target-spreadOnX",
(AT."targetShape"[22] ->> 'target-spreadOnY') :: numeric(3, 2)            "task22_target-spreadOnY",
(AT."targetShape"[22] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task22_target-spreadOnZ",
(AT."targetShape"[22] ->> 'target-totalBlocks') :: integer                "task22_target-totalBlocks",
(AT."targetShape"[22] ->> 'target-finalRotationX') :: numeric(3, 2)       "task22_target-finalRotationX",
(AT."targetShape"[22] ->> 'target-finalRotationY') :: numeric(3, 2)       "task22_target-finalRotationY",
(AT."targetShape"[22] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task22_target-finalRotationZ",
(AT."targetShape"[22] ->> 'target-maxDeltaForNextBlock') :: integer       "task22_target-maxDeltaForNextBlock",
(AT."images"[22] ->> 'scene') :: text                                     "task22_img-scene",
(AT."images"[22] ->> 'testShape') :: text                                 "task22_img-testShape",
(AT."images"[22] ->> 'testShape1') :: text                                "task22_img-testShape1",
(AT."images"[22] ->> 'testShape2') :: text                                "task22_img-testShape2",
(AT."images"[22] ->> 'testShape3') :: text                                "task22_img-testShape3",
(AT."images"[22] ->> 'testShape4') :: text                                "task22_img-testShape4",
(AT."images"[22] ->> 'testShape5') :: text                                "task22_img-testShape5",
(AT."images"[22] ->> 'referenceShape') :: text                            "task22_img-referenceShape",
(AT."images"[22] ->> 'referenceShapeRotated') :: text                     "task22_img-referenceShapeRotated",
AT."correctAnswer"[22]                                                    "task22_correctAnswer",

--     task 23
(AT.angles[23] ->> 'rotationX'):: integer                                 "task23_rotationX",
(AT.angles[23] ->> 'rotationY'):: integer                                 "task23_rotationY",
(AT.angles[23] ->> 'rotationZ'):: integer                                 "task23_rotationZ",
(AT."referenceShape"[23] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task23_reference-spreadOnX",
(AT."referenceShape"[23] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task23_reference-spreadOnY",
(AT."referenceShape"[23] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task23_reference-spreadOnZ",
(AT."referenceShape"[23] ->> 'reference-totalBlocks') :: integer          "task23_reference-totalBlocks",
(AT."referenceShape"[23] ->> 'reference-finalRotationX') :: numeric(3, 2) "task23_reference-finalRotationX",
(AT."referenceShape"[23] ->> 'reference-finalRotationY') :: numeric(3, 2) "task23_reference-finalRotationY",
(AT."referenceShape"[23] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task23_reference-finalRotationZ",
(AT."referenceShape"[23] ->> 'reference-maxDeltaForNextBlock') :: integer "task23_reference-maxDeltaForNextBlock",
(AT."targetShape"[23] ->> 'target-spreadOnX') :: numeric(3, 2)            "task23_target-spreadOnX",
(AT."targetShape"[23] ->> 'target-spreadOnY') :: numeric(3, 2)            "task23_target-spreadOnY",
(AT."targetShape"[23] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task23_target-spreadOnZ",
(AT."targetShape"[23] ->> 'target-totalBlocks') :: integer                "task23_target-totalBlocks",
(AT."targetShape"[23] ->> 'target-finalRotationX') :: numeric(3, 2)       "task23_target-finalRotationX",
(AT."targetShape"[23] ->> 'target-finalRotationY') :: numeric(3, 2)       "task23_target-finalRotationY",
(AT."targetShape"[23] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task23_target-finalRotationZ",
(AT."targetShape"[23] ->> 'target-maxDeltaForNextBlock') :: integer       "task23_target-maxDeltaForNextBlock",
(AT."images"[23] ->> 'scene') :: text                                     "task23_img-scene",
(AT."images"[23] ->> 'testShape') :: text                                 "task23_img-testShape",
(AT."images"[23] ->> 'testShape1') :: text                                "task23_img-testShape1",
(AT."images"[23] ->> 'testShape2') :: text                                "task23_img-testShape2",
(AT."images"[23] ->> 'testShape3') :: text                                "task23_img-testShape3",
(AT."images"[23] ->> 'testShape4') :: text                                "task23_img-testShape4",
(AT."images"[23] ->> 'testShape5') :: text                                "task23_img-testShape5",
(AT."images"[23] ->> 'referenceShape') :: text                            "task23_img-referenceShape",
(AT."images"[23] ->> 'referenceShapeRotated') :: text                     "task23_img-referenceShapeRotated",
AT."correctAnswer"[23]                                                    "task23_correctAnswer",

--     task 24
(AT.angles[24] ->> 'rotationX'):: integer                                 "task24_rotationX",
(AT.angles[24] ->> 'rotationY'):: integer                                 "task24_rotationY",
(AT.angles[24] ->> 'rotationZ'):: integer                                 "task24_rotationZ",
(AT."referenceShape"[24] ->> 'reference-spreadOnX') :: numeric(3, 2)      "task24_reference-spreadOnX",
(AT."referenceShape"[24] ->> 'reference-spreadOnY') :: numeric(3, 2)      "task24_reference-spreadOnY",
(AT."referenceShape"[24] ->> 'reference-spreadOnZ') :: numeric(3, 2)      "task24_reference-spreadOnZ",
(AT."referenceShape"[24] ->> 'reference-totalBlocks') :: integer          "task24_reference-totalBlocks",
(AT."referenceShape"[24] ->> 'reference-finalRotationX') :: numeric(3, 2) "task24_reference-finalRotationX",
(AT."referenceShape"[24] ->> 'reference-finalRotationY') :: numeric(3, 2) "task24_reference-finalRotationY",
(AT."referenceShape"[24] ->> 'reference-finalRotationZ') :: numeric(3, 2) "task24_reference-finalRotationZ",
(AT."referenceShape"[24] ->> 'reference-maxDeltaForNextBlock') :: integer "task24_reference-maxDeltaForNextBlock",
(AT."targetShape"[24] ->> 'target-spreadOnX') :: numeric(3, 2)            "task24_target-spreadOnX",
(AT."targetShape"[24] ->> 'target-spreadOnY') :: numeric(3, 2)            "task24_target-spreadOnY",
(AT."targetShape"[24] ->> 'target-spreadOnZ') :: numeric(3, 2)            "task24_target-spreadOnZ",
(AT."targetShape"[24] ->> 'target-totalBlocks') :: integer                "task24_target-totalBlocks",
(AT."targetShape"[24] ->> 'target-finalRotationX') :: numeric(3, 2)       "task24_target-finalRotationX",
(AT."targetShape"[24] ->> 'target-finalRotationY') :: numeric(3, 2)       "task24_target-finalRotationY",
(AT."targetShape"[24] ->> 'target-finalRotationZ') :: numeric(3, 2)       "task24_target-finalRotationZ",
(AT."targetShape"[24] ->> 'target-maxDeltaForNextBlock') :: integer       "task24_target-maxDeltaForNextBlock",
(AT."images"[24] ->> 'scene') :: text                                     "task24_img-scene",
(AT."images"[24] ->> 'testShape') :: text                                 "task24_img-testShape",
(AT."images"[24] ->> 'testShape1') :: text                                "task24_img-testShape1",
(AT."images"[24] ->> 'testShape2') :: text                                "task24_img-testShape2",
(AT."images"[24] ->> 'testShape3') :: text                                "task24_img-testShape3",
(AT."images"[24] ->> 'testShape4') :: text                                "task24_img-testShape4",
(AT."images"[24] ->> 'testShape5') :: text                                "task24_img-testShape5",
(AT."images"[24] ->> 'referenceShape') :: text                            "task24_img-referenceShape",
(AT."images"[24] ->> 'referenceShapeRotated') :: text                     "task24_img-referenceShapeRotated",
AT."correctAnswer"[24]                                                    "task24_correctAnswer",

AT.id,
AT.name,
AT.description
       from (select Te.id,
                    Te.name,
                    Te.description,
                    array_agg(Ta."referenceShape") "referenceShape",
                    array_agg(Ta."targetShape")    "targetShape",
                    array_agg(Ta."angles")         "angles",
                    array_agg(Ta."images")         "images",
                    array_agg(Ta."correctAnswer")  "correctAnswer"
             from "Test" Te
                      join "Task" Ta on TE.id = Ta."testId"
             group by Te.id, name, description) AT) "TestData"
          join (select * from get_actual_test_data()) "ActualTestData" on "TestData".id = "ActualTestData"."testId"
          join (select * from get_user_info_data()) "UserInfo" on "UserInfo"."userId" = "ActualTestData"."userId"
          join (select * from get_emotion_test_data()) "EmotionData"
               on "EmotionData"."userId" = "ActualTestData"."userId"
          join (select *
                from get_depression_test_data()) "DepressionData"
               on "DepressionData"."userId" = "ActualTestData"."userId");

select *
from get_user_info_data();

select *
from get_emotion_test_data();

select *
from get_depression_test_data();

select *
from get_actual_test_data()


-- SELECT *
-- FROM crosstab3(
--   'select rowid, attribute, value
--    from ct
--    where attribute = ''att2'' or attribute = ''att3''
--    order by 1,2');


-- select * from